info:
  app:
    description: Spring 5 Webflux Kotlin REST API Demo

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

spring:
  application:
    name: spring-webflux-kotlin